### ISSUE TITLE
Sample URLs on the progress bar demo hard to spot?

### ISSUE THREAD

**Issue by ricea** [TejasQ/basically-streams#5]
I didn't spot the sample images the first time I looked at the page. Maybe I am just unobservant, but my eyes didn't go down past the input box. A few ideas:
* Mention the sample images further up
* Pre-fill the input box with one of the sample image URLs (which vanishes when you start to enter a new one)
* Move the sample URLs up above the input box

**Comment by TejasQ** [comment]
Thanks for providing the ideas! They make a lot of sense. I'll implement these now.
